// This content is generated by AI (Kiro)
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import {
  CLAUDE_EXIT_MS, CLAUDE_START_ACK_MS, claudeCommand, claudeOutcome, claudePrompt, claudeTools,
  prepareClaudeRun, readClaudeSessionId, readClaudeState, tickClaudeRun, type ClaudeRun,
} from "../pi-extension/subagents/claude.ts";
import { errorReceiptFile } from "../pi-extension/subagents/process-run.ts";
import { __test__ } from "../pi-extension/subagents/index.ts";
import { createStatusState } from "../pi-extension/subagents/status.ts";

const session = "33333333-3333-4333-8333-333333333333";
const other = "44444444-4444-4444-8444-444444444444";

function withDir(fn: (dir: string) => void | Promise<void>) {
  const dir = mkdtempSync(join(tmpdir(), "claude-adapter-test-"));
  return Promise.resolve().then(() => fn(dir)).finally(() => rmSync(dir, { recursive: true, force: true }));
}

function makeRun(dir: string, options?: { id?: string; autoExit?: boolean; resume?: boolean; sessionId?: string }): ClaudeRun {
  const id = options?.id ?? "run-a";
  return prepareClaudeRun({ artifactDir: dir, processRun: { id, receiptFile: join(dir, `${id}.json`) }, cwd: dir,
    sessionId: options?.sessionId ?? session, resume: options?.resume ?? false, autoExit: options?.autoExit ?? true });
}

/** Run the hook exactly as configured in the per-run --settings file. */
function hook(run: ClaudeRun, kind: string, extra: Record<string, unknown> = {}, sessionId = run.sessionId) {
  const settings = JSON.parse(readFileSync(run.settingsFile, "utf8"));
  const command = settings.hooks[kind][0].hooks[0].command;
  const result = spawnSync("bash", ["-c", command], { encoding: "utf8",
    input: JSON.stringify({ hook_event_name: kind, session_id: sessionId, transcript_path: "/x.jsonl", cwd: "/elsewhere", ...extra }) });
  assert.equal(result.stdout, "", "hook stdout would become model context");
  return result;
}

const prompt = (run: ClaudeRun, text = "task") => hook(run, "UserPromptSubmit", { prompt: claudePrompt(text, run.expectedToken) });
const stop = (run: ClaudeRun, text: string, extra: Record<string, unknown> = {}) =>
  hook(run, "Stop", { stop_hook_active: false, last_assistant_message: text, ...extra });

describe("native interactive Claude adapter", () => {
  it("requires explicit representable permissions, rejects unsupported profile capabilities", () => {
    assert.equal(claudeTools("read,edit,read"), "Read,Edit");
    assert.equal(claudeTools("read,grep,find,ls"), "Read,Grep,Glob");
    for (const tools of [undefined, "", "read,web_search", "read,safe_bash", "read,ls"]) {
      assert.throws(() => claudeTools(tools), /require an explicit|cannot safely map|find with ls/);
    }
    assert.throws(() => claudeTools("read", { spawnable: ["scout"] }), /cannot use/);
    assert.throws(() => claudeTools("read", { skills: "web" }), /cannot auto-load/);
    assert.throws(() => claudeTools("read", { sessionMode: "fork" }), /only support standalone/);
    assert.throws(() => claudeTools("read", { thinking: "minimal" }), /thinking level/);
    assert.equal(claudeTools("read", { thinking: "high" }), "Read");
  });

  it("launches/resumes the exact UUID in its cwd with manual permissions, no MCP and no pre-approval", async () => withDir((dir) => {
    const initial = claudeCommand(makeRun(dir, { id: "a" }), "benign", { tools: "Read" });
    const resumed = claudeCommand(makeRun(dir, { id: "b", resume: true }), "follow-up", { tools: "Read" });
    assert.match(initial, new RegExp(`--session-id '${session}' '\\[pi-subagent-turn:`));
    assert.match(resumed, new RegExp(`--resume '${session}' '\\[pi-subagent-turn:`));
    assert.doesNotMatch(resumed, /--session-id/);
    for (const command of [initial, resumed]) {
      assert.ok(command.startsWith(`cd '${dir}' && claude `));
      assert.match(command, /--permission-mode manual --strict-mcp-config --tools 'Read' --settings /);
      assert.doesNotMatch(command, /dangerously|bypass|allowedTools|--mcp-config|--print|-p |stream-json/);
    }
    const replaced = claudeCommand(makeRun(dir, { id: "c" }), "x", { tools: "Read", identity: "ROLE", promptMode: "replace", thinking: "high", model: "sonnet" });
    assert.match(replaced, /--model 'sonnet' --effort 'high' --system-prompt 'ROLE' --session-id/);
  }));

  it("isolates concurrent same-cwd runs: exclusive per-run settings, config and state", async () => withDir((dir) => {
    const a = makeRun(dir, { id: "a" });
    const b = makeRun(dir, { id: "b", sessionId: other });
    assert.notEqual(a.settingsFile, b.settingsFile);
    const settingsA = readFileSync(a.settingsFile, "utf8");
    assert.ok(settingsA.includes(a.configFile) && !settingsA.includes(b.configFile));
    assert.deepEqual(Object.keys(JSON.parse(settingsA).hooks).sort(), ["SessionStart", "Stop", "StopFailure", "UserPromptSubmit"]);
    // A relaunch with a reused run id can never silently retarget an existing child's hooks.
    assert.throws(() => makeRun(dir, { id: "a" }), /EEXIST/);
    assert.equal(readFileSync(a.settingsFile, "utf8"), settingsA);
    prompt(a); stop(a, "A");
    prompt(b); stop(b, "B");
    assert.equal(readClaudeState(a)?.summary, "A");
    assert.equal(readClaudeState(b)?.summary, "B");
    // Hooks of one child cannot write into another's identity.
    assert.equal(hook(a, "Stop", { last_assistant_message: "X" }, other).status, 1);
    assert.equal(readClaudeState(a)?.summary, "A");
  }));

  it("correlates only the tagged prompt's Stop; stale, untagged, overlapping and failed turns never complete", async () => withDir((dir) => {
    const run = makeRun(dir);
    assert.equal(hook(run, "SessionStart", { source: "startup" }).status, 0);
    assert.equal(readClaudeState(run)?.phase, "ready");
    stop(run, "stale before any prompt");
    assert.equal(readClaudeState(run)?.phase, "ready");
    prompt(run);
    assert.equal(readClaudeState(run)?.phase, "active");
    stop(run, "FIRST");
    assert.deepEqual([readClaudeState(run)?.phase, readClaudeState(run)?.summary], ["stopped", "FIRST"]);
    // Duplicate/late Stop does not overwrite the correlated result.
    stop(run, "LATE");
    assert.equal(readClaudeState(run)?.summary, "FIRST");
    // A later Stop hook continuation of the same turn keeps its latest text.
    stop(run, "CONTINUED", { stop_hook_active: true });
    assert.equal(readClaudeState(run)?.summary, "CONTINUED");
    hook(run, "UserPromptSubmit", { prompt: "untagged human turn" });
    stop(run, "HUMAN");
    assert.deepEqual([readClaudeState(run)?.phase, readClaudeState(run)?.token], ["untracked", null]);
    // Overlap: a prompt submitted while a turn is active is unattributable even if tagged.
    prompt(run, "one");
    prompt(run, "two");
    stop(run, "AMBIGUOUS");
    assert.equal(readClaudeState(run)?.phase, "untracked");
    prompt(run);
    hook(run, "StopFailure", { error: "rate_limit", error_details: "429", last_assistant_message: "" });
    assert.deepEqual([readClaudeState(run)?.phase, readClaudeState(run)?.error], ["failed", "rate_limit: 429"]);
    prompt(run);
    stop(run, "   ");
    assert.equal(readClaudeState(run)?.phase, "failed");
  }));

  it("a changed native session (e.g. /clear or a forked resume) fails the run instead of being adopted", async () => withDir((dir) => {
    const run = makeRun(dir);
    const result = hook(run, "SessionStart", { source: "clear" }, other);
    assert.equal(result.status, 1);
    assert.match(readFileSync(errorReceiptFile({ id: run.id, receiptFile: join(dir, `${run.id}.json`) }), "utf8"), /session ID changed/);
    assert.equal(readClaudeState(run), null);
  }));

  it("queues follow-ups until a correlated Stop, then exits gracefully instead of killing the TUI", async () => withDir((dir) => {
    const run = makeRun(dir);
    const sent: string[] = [];
    const send = (text: string) => sent.push(text);
    const t0 = run.submittedAt;
    tickClaudeRun(run, send, t0 + 1000);
    prompt(run);
    run.pendingMessages.push("also check\nthe tests");
    tickClaudeRun(run, send, t0 + 2000);
    assert.deepEqual(sent, [], "never typed into a busy TUI");
    const firstToken = run.expectedToken;
    stop(run, "FIRST");
    tickClaudeRun(run, send, t0 + 3000);
    assert.equal(sent.length, 1);
    assert.notEqual(run.expectedToken, firstToken);
    assert.equal(sent[0], `[pi-subagent-turn:${run.expectedToken}] also check the tests`);
    // Old token's receipt is not the follow-up's completion.
    tickClaudeRun(run, send, t0 + 4000);
    assert.equal(sent.length, 1);
    assert.equal(claudeOutcome(run, { reason: "done", exitCode: 0 }).completed, false);
    hook(run, "UserPromptSubmit", { prompt: sent[0] });
    stop(run, "SECOND");
    tickClaudeRun(run, send, t0 + 5000);
    assert.deepEqual(sent.slice(1), ["/exit"]);
    tickClaudeRun(run, send, t0 + 5000 + CLAUDE_EXIT_MS);
    assert.equal(sent.length, 2, "/exit is sent once");
    assert.throws(() => tickClaudeRun(run, send, t0 + 5001 + CLAUDE_EXIT_MS), /did not exit/);
    assert.deepEqual(claudeOutcome(run, { reason: "done", exitCode: 0 }), { completed: true, summary: "SECOND" });
    assert.equal(claudeOutcome(run, { reason: "done", exitCode: 1 }).completed, false);
    assert.equal(claudeOutcome(run, { reason: "error", exitCode: 0, errorMessage: "hook" }).completed, false);
  }));

  it("interactive profiles stay open; human input fails closed only for autonomous runs", async () => withDir((dir) => {
    const interactive = makeRun(dir, { id: "i", autoExit: false });
    const sent: string[] = [];
    prompt(interactive); stop(interactive, "DONE");
    hook(interactive, "UserPromptSubmit", { prompt: "human question" });
    stop(interactive, "HUMAN ANSWER");
    tickClaudeRun(interactive, (text) => sent.push(text));
    assert.deepEqual(sent, []);
    assert.equal(claudeOutcome(interactive, { reason: "done", exitCode: 0 }).completed, false);

    const auto = makeRun(dir, { id: "a" });
    prompt(auto);
    hook(auto, "UserPromptSubmit", { prompt: "human typed mid-turn" });
    assert.throws(() => tickClaudeRun(auto, () => {}), /Unexpected human input/);
  }));

  it("an API-failed autonomous turn exits gracefully and reports the native error", async () => withDir((dir) => {
    const run = makeRun(dir);
    const sent: string[] = [];
    prompt(run);
    hook(run, "StopFailure", { error: "authentication_failed" });
    tickClaudeRun(run, (text) => sent.push(text));
    assert.deepEqual(sent, ["/exit"]);
    const outcome = claudeOutcome(run, { reason: "done", exitCode: 0 });
    assert.equal(outcome.completed, false);
    assert.match(outcome.summary, /turn failed: authentication_failed/);
  }));

  it("unacknowledged launches fail with a human-dialog hint, without answering anything", async () => withDir((dir) => {
    const run = makeRun(dir);
    const sent: string[] = [];
    hook(run, "SessionStart", { source: "startup" });
    tickClaudeRun(run, (text) => sent.push(text), run.submittedAt + CLAUDE_START_ACK_MS);
    assert.throws(() => tickClaudeRun(run, (text) => sent.push(text), run.submittedAt + CLAUDE_START_ACK_MS + 1),
      /did not acknowledge.*workspace trust.*No dialog was answered/);
    assert.deepEqual(sent, []);
  }));

  it("running messages are queued (never typed immediately) and exiting runs refuse input", async () => withDir((dir) => {
    const run = makeRun(dir);
    const running: any = { id: "x", name: "claude-worker", surface: "w1:p9", cli: "claude", claude: run,
      processRun: { id: run.id, receiptFile: join(dir, "live.json") }, interactive: false,
      statusState: createStatusState({ source: "claude", startTimeMs: Date.now() }), startTime: Date.now() };
    __test__.runningSubagents.set(running.id, running);
    try {
      let writes = 0;
      const result = __test__.handleSubagentSteer({ name: "claude-worker", message: "follow-up" },
        () => { writes++; }, () => true);
      assert.equal(result.details.status, "queued");
      assert.deepEqual(run.pendingMessages, ["follow-up"]);
      run.quittingAt = Date.now();
      const refused = __test__.handleSubagentSteer({ name: "claude-worker", message: "late" }, () => { writes++; }, () => true);
      assert.match(refused.details.error ?? "", /exiting/);
      assert.equal(writes, 0);
    } finally { __test__.runningSubagents.delete(running.id); }
  }));

  it("resume identity comes only from the owned external-session marker", async () => withDir((dir) => {
    const file = join(dir, "marker.jsonl");
    writeFileSync(file, JSON.stringify({ type: "external_session", harness: "claude", nativeSessionId: session }) + "\n");
    assert.equal(readClaudeSessionId(file), session);
    for (const bad of [{ harness: "kiro", nativeSessionId: session }, { harness: "claude", nativeSessionId: "latest" }]) {
      writeFileSync(file, JSON.stringify({ type: "external_session", ...bad }) + "\n");
      assert.equal(readClaudeSessionId(file), null);
    }
    assert.equal(readClaudeSessionId(join(dir, "missing")), null);
    assert.ok(!existsSync(join(dir, ".claude")), "no workspace/global Claude config is written");
  }));
});

describe("bundled claude-worker profile", () => {
  it("is autonomous and representable without broadening its declared tools", () => {
    const defs: any = __test__.loadAgentDefaults("claude-worker");
    assert.ok(defs, "expected bundled claude-worker to be discoverable");
    assert.equal(defs.cli, "claude");
    assert.equal(defs.autoExit, true);
    assert.equal(__test__.resolveEffectiveInteractive({ name: "claude-worker", task: "" }, defs), false);
    assert.equal(claudeTools(defs.tools, { spawnable: defs.subagentAgents, skills: defs.skills,
      sessionMode: defs.sessionMode, thinking: defs.thinking }), "Read,Grep,Glob,Write,Edit,Bash");
  });
});
