// This content is generated by AI (Kiro)
/** Native interactive Claude Code TUI. No -p/stream-JSON/SDK or screen-extraction fallback. */
import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { errorReceiptFile, type ProcessRun } from "./process-run.ts";
import { shellEscape } from "./shell.ts";

export const claudeHookPath = join(dirname(fileURLToPath(import.meta.url)), "plugin/hooks/claude-lifecycle.py");
export const newClaudeId = (): string => randomUUID();
const UUID = /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/;
export const isClaudeSessionId = (value: unknown): value is string => typeof value === "string" && UUID.test(value);
/** Launch may wait on a human-only startup dialog (workspace trust, login). */
export const CLAUDE_START_ACK_MS = 120_000;
export const CLAUDE_FOLLOW_UP_ACK_MS = 30_000;
export const CLAUDE_EXIT_MS = 15_000;
const EFFORT = ["low", "medium", "high", "xhigh", "max"];

export function claudePrompt(task: string, token: string): string {
  return `[pi-subagent-turn:${token}] ${task}`;
}

/** Fail closed when a Pi profile cannot be represented by the native Claude CLI. */
export function claudeTools(tools?: string, options?: {
  spawnable?: string[]; skills?: string; sessionMode?: string; thinking?: string | null;
}): string {
  if (options?.spawnable?.length) throw new Error("Claude profiles cannot use Pi subagent_agents/ask_question tools.");
  if (options?.skills) throw new Error("Claude profiles cannot auto-load Pi skills.");
  if (options?.sessionMode && options.sessionMode !== "standalone") {
    throw new Error("Claude profiles only support standalone sessions; Pi lineage/fork modes are not portable.");
  }
  if (options?.thinking && !EFFORT.includes(options.thinking)) {
    throw new Error(`Claude cannot represent thinking level ${options.thinking} (supported: ${EFFORT.join(", ")}).`);
  }
  if (!tools?.trim()) throw new Error("Claude profiles require an explicit tools allowlist.");
  const mapping: Record<string, string> = { read: "Read", write: "Write", edit: "Edit", bash: "Bash", grep: "Grep", find: "Glob", ls: "Glob" };
  const parsed = tools.split(",").map((tool) => tool.trim()).filter(Boolean);
  const unknown = parsed.filter((tool) => !mapping[tool]);
  if (!parsed.length || unknown.length) throw new Error(`Claude cannot safely map Pi tools: ${unknown.join(", ")}.`);
  // Claude has no directory-listing tool; Glob also searches recursively like
  // Pi's find. Do not silently grant an ls-only profile recursive search.
  if (parsed.includes("ls") && !parsed.includes("find")) throw new Error("Claude requires find with ls (one native Glob tool).");
  return [...new Set(parsed.map((tool) => mapping[tool]))].join(",");
}

export interface ClaudeState {
  version: 1;
  run_id: string;
  session_id: string;
  phase: "ready" | "active" | "stopped" | "failed" | "untracked";
  token: string | null;
  summary?: string | null;
  error?: string | null;
}

export interface ClaudeRun {
  id: string;
  cwd: string;
  sessionId: string;
  resume: boolean;
  settingsFile: string;
  configFile: string;
  stateFile: string;
  expectedToken: string;
  submittedAt: number;
  ackTimeoutMs: number;
  acknowledged: boolean;
  autoExit: boolean;
  pendingMessages: string[];
  quittingAt?: number;
}

/**
 * Per-run, exclusively created hook settings/config/state. A shared settings
 * file would let a concurrent launch (or Claude's settings hot-reload) retarget
 * another child's hooks. User/global/project settings are never edited.
 */
export function prepareClaudeRun(options: {
  artifactDir: string; processRun: ProcessRun; cwd: string; sessionId: string; resume: boolean; autoExit: boolean;
}): ClaudeRun {
  if (!isClaudeSessionId(options.sessionId)) throw new Error("Invalid native Claude session ID.");
  const root = join(options.artifactDir, "claude-runs", options.processRun.id);
  mkdirSync(root, { recursive: true, mode: 0o700 });
  const run: ClaudeRun = {
    id: options.processRun.id, cwd: resolve(options.cwd), sessionId: options.sessionId, resume: options.resume,
    settingsFile: join(root, "settings.json"), configFile: join(root, "hook-config.json"), stateFile: join(root, "state.json"),
    expectedToken: randomUUID(), submittedAt: Date.now(), ackTimeoutMs: CLAUDE_START_ACK_MS, acknowledged: false,
    autoExit: options.autoExit, pendingMessages: [],
  };
  writeFileSync(run.configFile, JSON.stringify({ version: 1, run_id: run.id, expected_session_id: run.sessionId,
    state_file: run.stateFile, error_file: errorReceiptFile(options.processRun) }), { flag: "wx", mode: 0o600 });
  const command = `python3 ${shellEscape(claudeHookPath)} ${shellEscape(run.configFile)}`;
  const hook = [{ hooks: [{ type: "command", command, timeout: 10 }] }];
  writeFileSync(run.settingsFile, JSON.stringify({ hooks: {
    SessionStart: hook, UserPromptSubmit: hook, Stop: hook, StopFailure: hook,
  } }, null, 2) + "\n", { flag: "wx", mode: 0o600 });
  return run;
}

export function readClaudeState(run: ClaudeRun): ClaudeState | null {
  try {
    const data = JSON.parse(readFileSync(run.stateFile, "utf8"));
    if (data.version !== 1 || data.run_id !== run.id || data.session_id !== run.sessionId ||
      !["ready", "active", "stopped", "failed", "untracked"].includes(data.phase) ||
      (data.token !== null && !isClaudeSessionId(data.token))) return null;
    if (data.phase === "stopped" && (typeof data.summary !== "string" || !data.summary.trim() || !data.token)) return null;
    return data;
  } catch { return null; }
}

export function claudeCommand(run: ClaudeRun, task: string, options: {
  tools: string; model?: string | null; thinking?: string | null;
  identity?: string | null; promptMode?: "append" | "replace" | null;
}): string {
  // Autonomous children cannot answer approval prompts. Bypass approvals for
  // the explicit --tools allowlist only; unavailable tools stay unavailable.
  // --strict-mcp-config without --mcp-config loads zero MCP servers, including
  // inherited user/project/plugin configuration.
  const args = ["claude", "--permission-mode", "bypassPermissions", "--dangerously-skip-permissions",
    "--strict-mcp-config", "--tools", shellEscape(options.tools),
    "--settings", shellEscape(run.settingsFile)];
  if (options.model) args.push("--model", shellEscape(options.model));
  if (options.thinking) args.push("--effort", shellEscape(options.thinking));
  if (options.identity) args.push(options.promptMode === "replace" ? "--system-prompt" : "--append-system-prompt", shellEscape(options.identity));
  // Single-valued option last, so no variadic option can consume the prompt.
  args.push(run.resume ? "--resume" : "--session-id", shellEscape(run.sessionId));
  args.push(shellEscape(claudePrompt(task, run.expectedToken)));
  return `cd ${shellEscape(run.cwd)} && ${args.join(" ")}`;
}

/**
 * Submit parent follow-ups only at a verified correlated Stop (typing into a
 * busy TUI could inject mid-turn or answer an approval prompt), and exit
 * autonomous runs with /exit so native history persists before any resume.
 */
export function tickClaudeRun(run: ClaudeRun, send: (text: string) => void, now = Date.now()): void {
  if (run.quittingAt !== undefined) {
    if (now - run.quittingAt > CLAUDE_EXIT_MS) throw new Error("Claude Code did not exit after /exit; native resume persistence is unconfirmed.");
    return;
  }
  const state = readClaudeState(run);
  if (state?.token === run.expectedToken && state.phase !== "ready") run.acknowledged = true;
  if (!run.acknowledged && now - run.submittedAt > run.ackTimeoutMs) {
    throw new Error(`Claude Code did not acknowledge the tagged prompt within ${Math.round(run.ackTimeoutMs / 1000)} seconds ` +
      "(hooks disabled, or a startup dialog such as workspace trust is waiting for a human). No dialog was answered.");
  }
  if (!state) return;
  if (run.autoExit && state.phase !== "ready" && (!state.token || (run.acknowledged && state.token !== run.expectedToken))) {
    throw new Error("Unexpected human input superseded the autonomous Claude turn; refusing ambiguous completion.");
  }
  const current = state.token === run.expectedToken;
  const completed = current && state.phase === "stopped";
  const failed = current && state.phase === "failed";
  if (run.pendingMessages.length && (completed || state.phase === "untracked" || (failed && !run.autoExit))) {
    const task = run.pendingMessages.join("\n\n");
    run.expectedToken = randomUUID();
    run.submittedAt = now;
    run.ackTimeoutMs = CLAUDE_FOLLOW_UP_ACK_MS;
    run.acknowledged = false;
    run.pendingMessages = [];
    send(claudePrompt(task, run.expectedToken).replace(/\s*\n\s*/g, " "));
  } else if ((completed || failed) && run.autoExit) {
    run.quittingAt = now;
    send("/exit");
  }
}

/** Only the current run's correlated final Stop is a successful result. */
export function claudeOutcome(run: ClaudeRun, exit: { reason: string; exitCode: number; errorMessage?: string }):
  { completed: true; summary: string } | { completed: false; summary: string } {
  const state = readClaudeState(run);
  const current = state?.token === run.expectedToken;
  if (exit.reason !== "error" && exit.exitCode === 0 && current && state?.phase === "stopped" && !run.pendingMessages.length) {
    return { completed: true, summary: state.summary!.trim() };
  }
  const reason = current && state?.phase === "failed" ? `turn failed: ${state.error ?? "unknown error"}`
    : run.pendingMessages.length ? `${run.pendingMessages.length} queued message(s) were never submitted`
      : exit.errorMessage ?? `shell exit ${exit.exitCode}`;
  return { completed: false, summary: `Claude Code exited without a correlated final Stop receipt (${reason}).` };
}

/** Identity comes from the owned marker written at spawn, never "latest in cwd". */
export function readClaudeSessionId(sessionFile: string): string | null {
  try {
    const data = JSON.parse(readFileSync(sessionFile, "utf8"));
    return data.type === "external_session" && data.harness === "claude" && isClaudeSessionId(data.nativeSessionId)
      ? data.nativeSessionId : null;
  } catch { return null; }
}
