#!/usr/bin/env python3
# This content is generated by AI (Kiro)
"""Claude Code hooks: locked, atomic, native-session/turn-correlated receipts.

The TUI stays interactive. Only a Stop for the expected launch session after
one tagged UserPromptSubmit can complete the parent watcher. No screen text,
stale Stop, transcript guess or 'latest session in cwd' is ever a result.
Never write stdout: UserPromptSubmit/SessionStart stdout becomes model context.
"""
import fcntl
import json
import os
import re
import sys
import tempfile

UUID = re.compile(r"^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$")
TOKEN = re.compile(r"^\[pi-subagent-turn:([0-9a-f-]{36})\](?:\s|$)")


def atomic(path, value):
    fd, temp = tempfile.mkstemp(prefix="claude-hook-", dir=os.path.dirname(path))
    try:
        with os.fdopen(fd, "w", encoding="utf8") as stream:
            json.dump(value, stream)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp, path)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)


def main(config):
    event = json.load(sys.stdin)
    session = event.get("session_id")
    if not isinstance(session, str) or not UUID.fullmatch(session):
        raise ValueError("missing/invalid native session ID")
    if session != config["expected_session_id"]:
        # e.g. /clear or a resume that forked: the stored identity is no longer
        # the one this run can resume.
        raise ValueError("native session ID changed from the launched/resumed session")
    kind = event.get("hook_event_name")

    with open(config["state_file"] + ".lock", "a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        try:
            with open(config["state_file"], encoding="utf8") as stream:
                state = json.load(stream)
        except FileNotFoundError:
            state = {"version": 1, "run_id": config["run_id"], "session_id": session,
                     "phase": "ready", "token": None}
        if state.get("run_id") != config["run_id"] or state.get("session_id") != session:
            raise ValueError("hook run/session identity changed")

        if kind == "SessionStart":
            pass  # startup/resume/compact: identity check only
        elif kind == "UserPromptSubmit":
            prompt = event.get("prompt")
            if not isinstance(prompt, str):
                raise ValueError("prompt hook has no prompt string")
            match = TOKEN.match(prompt)
            # A prompt arriving while a turn is active (queued human input)
            # makes the eventual Stop unattributable: never guess.
            token = match.group(1) if match and state["phase"] != "active" else None
            state = {**state, "phase": "active", "token": token, "summary": None, "error": None}
        elif kind == "Stop":
            summary = event.get("last_assistant_message")
            if event.get("stop_hook_active") and state["phase"] == "stopped" and state["token"] \
                    and isinstance(summary, str) and summary.strip():
                # Another Stop hook made the same turn continue: keep its latest text.
                state = {**state, "summary": summary.strip()}
            elif state["phase"] != "active":
                return  # duplicate/late Stop without a submitted turn
            elif not state["token"]:
                state = {**state, "phase": "untracked"}
            else:
                if isinstance(summary, str) and summary.strip():
                    state = {**state, "phase": "stopped", "summary": summary.strip()}
                else:
                    state = {**state, "phase": "failed", "error": "Stop hook had no final assistant text"}
        elif kind == "StopFailure":
            if state["phase"] != "active":
                return
            if not state["token"]:
                state = {**state, "phase": "untracked"}
            else:
                details = event.get("error_details")
                error = str(event.get("error") or "unknown")
                if isinstance(details, str) and details.strip():
                    error += ": " + details.strip()
                state = {**state, "phase": "failed", "error": error[:500]}
        else:
            raise ValueError("unexpected hook event")
        atomic(config["state_file"], state)


if __name__ == "__main__":
    config = None
    try:
        with open(sys.argv[1], encoding="utf8") as stream:
            config = json.load(stream)
        main(config)
    except Exception as error:  # pylint: disable=broad-except
        message = "Claude lifecycle hook: " + str(error)
        if config:
            try:
                atomic(config["error_file"], {"type": "error", "errorMessage": message})
            except OSError:
                pass
        print(message, file=sys.stderr)
        # Exit 1 is non-blocking in Claude; 2 would block/alter the prompt.
        sys.exit(1)
