#!/usr/bin/env python3
# This content is generated by AI (Kiro)
"""Offline Claude Code stand-in for launch/resume wiring; never contacts a model."""
import json
import pathlib
import subprocess
import sys

args = sys.argv[1:]
assert "-p" not in args and "--print" not in args and "--output-format" not in args
assert not any("dangerously" in arg for arg in args) and "--allowedTools" not in args
assert args[args.index("--permission-mode") + 1] == "manual"
assert "--strict-mcp-config" in args and "--mcp-config" not in args
assert args[args.index("--tools") + 1] == "Read"
settings = json.loads(pathlib.Path(args[args.index("--settings") + 1]).read_text())
saved = pathlib.Path(".fake-claude-session.json")
if "--resume" in args:
    sid = args[args.index("--resume") + 1]
    assert sid == json.loads(saved.read_text())["session_id"], "resume must reopen the exact native session"
    assert "--session-id" not in args
    source = "resume"
else:
    sid = args[args.index("--session-id") + 1]
    saved.write_text(json.dumps({"session_id": sid}))
    source = "startup"
prompt = args[-1]
assert prompt.startswith("[pi-subagent-turn:")
for kind, extra in [("SessionStart", {"source": source}), ("UserPromptSubmit", {"prompt": prompt}),
                    ("Stop", {"stop_hook_active": False, "last_assistant_message": "Claude fixture result"})]:
    payload = {"hook_event_name": kind, "cwd": str(pathlib.Path.cwd()), "session_id": sid,
               "transcript_path": "/nonexistent/fixture.jsonl", **extra}
    for group in settings["hooks"][kind]:
        for hook in group["hooks"]:
            result = subprocess.run(hook["command"], shell=True, input=json.dumps(payload), text=True, capture_output=True)
            assert result.returncode == 0, result.stderr
            assert result.stdout == ""
# Model nothing; exit like a TUI after /exit.
